### ISSUE TITLE
Confused by workflow

### ISSUE THREAD

**Issue by mrclay** [usdoj/foia.gov#1652]
Should new work be based on the `master` branch? or `develop`?

Because the docs suggest opening a PR against `master` but the PRs I see all target `develop`.

What's the base branch we should build on, and to which branch should we point PRs? (We probably won't send regular PRs until later in development)

**Comment by brockfanning** [comment]
@mrclay In general the latest code is in develop. But actually for your purposes, I've started a new branch (in both repos) called "uat-forumone". Please use uat-forumone as the base branch for all your PRs. This way, when they are merged, they'll automatically get deployed for our UAT environment. Meanwhile, we'll periodically update uat-forumone with the latest from develop, so that it doesn't lag behind.

**Comment by mrclay** [comment]
Thanks for the clarification.
