### ISSUE TITLE
Create or decide on a prototype to show people

### ISSUE THREAD

**Issue by RyanSibley** [usdoj/foia.gov#30]
As a design team we need to determine what artifact we'd like to demonstrate for users (if any) during interviews and usability sessions. @pkarman has suggested using the foia.gov site mirror he's created to create a prototype for testing: https://foia-dot-gov.app.cloud.gov/index.html

**Comment by pkarman** [comment]
Some points of information.
Today on foia.gov a requester can view the list of agencies and select one in order to find out how to submit a FOIA request to an office within that agency. Here's a snap of the final thing they see at https://www.foia.gov/report-makerequest.html after selecting an agency and an office.

![screen shot 2017-07-27 at 11 52 20 am](https://user-images.githubusercontent.com/1205061/28682474-b65df5f0-72c2-11e7-9ddb-d72743ed58cb.png)
