### ISSUE TITLE
Conditional Request Requirements - contact information

### ISSUE THREAD

**Issue by jhuang0427** [usdoj/foia.gov#605]
Requesters should be required to provide at least some measure of contact information (address, email, or phone). Some requesters have been sending requests to agencies without any contact information at all.  This makes the request essentially useless and the agency can’t do anything with it.

**Comment by jhuang0427** [comment]
Should we do some kind of validation on provided information?

**Comment by brockfanning** [comment]
@jhuang0427 I think the goal is to validate that users have entered something (anything) in at least one of:
* address
* email
* phone

**Comment by jhuang0427** [comment]
How about the format/criteria of each information

**Comment by brockfanning** [comment]
@mngardner @btalebian @gsolomon123 @vivbutler @cathyflanagan

@jhuang0427 has an approach for this up on the dev-www site. Can you try it out and give feedback?

**Comment by mngardner** [comment]
@brockfanning - this looks great.  Could we have it say:  "In order to submit your request, you must provide at least one of the following:  email address, mailing address, or fax number."  The goal is to ensure the agency can send correspondence to the requester some way.

**Comment by brockfanning** [comment]
@mngardner Cool. Did you maybe mean "phone number" instead of "fax number"?

**Comment by brockfanning** [comment]
@jhuang0427 Could you update the language to this?

"In order to submit your request, you must provide at least one of the following: email address, mailing address, or phone number."

Also, I think that if any of the three inputs are *already* required, that nothing should happen. For example, if a component has specifically required mailing address, then we don't want to allow requesters to use email instead. Can you wrap the whole thing in a conditional that asserts that all three inputs are not already required?

**Comment by brockfanning** [comment]
@mngardner We're trying out a refactoring of this with a different approach. What do you think about this experience?
![foia-contact-info-required](https://user-images.githubusercontent.com/1319083/39759802-9cf8adde-52a1-11e8-9bd8-d07f7c86f6fd.gif)

**Comment by mngardner** [comment]
@brockfanning  - that looks great!  We like it very much.
