### ISSUE TITLE
Agency info collection survey

### ISSUE THREAD

**Issue by RyanSibley** [usdoj/foia.gov#66]
As FOIA personnel within an agency, in order to communicate our perfected FOIA request needs, I need a way to validate fields and request new fields to populate the FOIA portal relevant to my agency.

## Acceptance criteria

- [Survey created in google forms ]
- [Survey reviewed and edited by 18F team ]
- [ Survey reviewed and approved by OIP]

**Comment by RyanSibley** [comment]
First draft of survey: https://docs.google.com/forms/d/e/1FAIpQLSfFLQxq2U830ZMAo5LSiMHAxTBy0ApsEk7iL3g3aO0mpHbzdA/viewform?usp=sf_link

Please submit feedback in comments.

**Comment by vz3** [comment]
My instinct is that we should not paginate every question. That’s a lot of additional clicks through the experience, and I think there is value  in allowing users to see all the questions they can expect to need to be able to answer. Interested in hearing what other folks think.

If we feel that this results in too long a form, perhaps we could break it up into 3-4 pages rather than 41.

I love the “Tell us in a few words what prompts this requirement” question.

“Not applicable” is confusing to me. I almost want to just see “No” or “Not needed” or something simpler.

Perhaps phrasing like this:

## E-mail address

*Does your agency require the requester's e-mail address?*

- [ ] No
- [ ] Yes, optional 
- [ ] Yes, required 
- [ ] Sometimes (We will ask for further detail)

# Some fields that should never be required:
Middle name
Organization
Fax number

# Requester’s email address

Just want to note that I hope this is required and I think will better serve requesters if it is.

# Requester’s Fax number

This could be a good place to consider testing how we discourage user hostile practices like requiring Fax number. If agency user selects `required`, X happens.

# Request description
Would like supplemental copy here. “This is the body of the request” or something like that. (Edit: Now that I went through the whole form I think it might be the ‘subject’.

# Certificate of identity
I like that you re-state with a question here. Could be a model for all other sections (Edit: Proposed question format above based on this).

# DOJ-351

Consider linking to form. Is this applicable outside of DOJ? I believe we heard that every agency can have their own DOJ-351, in which case supplemental copy could be helpful in place of a link.

# Date of birth

This is part of the “10%”, I would consider leaving this out. We allow agencies to enter this into “Did we miss anything”

# Alien number

Also part of the “10%”, would consider leaving out.

# Did we miss anything

Perhaps this could be page 2 of 2 if we combine the rest.

Perhaps something more open ended, like: Is there any other information your agency needs from requesters?

In the follow up-box, I recommend a large text box, with a prompt like “Describe the information that your agency needs from requesters that weren’t in this form”.

**Comment by hbillings** [comment]
The only thing I found going through is that I think the slide "Requester category such individual (non commercial), representative of the news media, educational, or commercial requester" is supposed to be "such as"?

**Comment by RyanSibley** [comment]
google form: https://docs.google.com/a/gsa.gov/forms/d/1YM6SN5ookWj0--xp8bxDff1x3flsaNPA3y8xcqA0ug8/edit?usp=sharing

**Comment by RyanSibley** [comment]
Being that we have a working draft, is this ok to close and open a new issue for testing? The excel version has been put on the back burner per a convo with @vz3.
